### ISSUE TITLE
This repository is too confusing

### ISSUE THREAD

**Issue by Ashwin-Iyer1** [Thinkerious/Deep-CNN-Image-of-Ashwin-Classifier#1]
Who is this "Ashwin"? Can I train this on anyone or just him?

**Comment by Thinkerious** [comment]
Hey Ashwin, I've made a tutorial video for you. Check it out below!

https://onlyfans.com/dhyan_patel/xxx-my-first-self-inflected-blue-balls-tortue-xxx
